name: Security Vulnerability (Public)
description: Report a non-critical security issue (Use private reporting for critical issues)
title: "[Security]: "
labels: ["security", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ IMPORTANT - Read First

        **For critical security vulnerabilities, please use GitHub's private reporting:**
        - Go to the Security tab
        - Click "Report a vulnerability"
        - Follow the private disclosure process

        **Only use this template for:**
        - Low-severity security improvements
        - Security-related feature requests
        - Public security discussions

  - type: checkboxes
    id: severity
    attributes:
      label: Severity Confirmation
      description: Please confirm this is not a critical vulnerability
      options:
        - label: This is NOT a critical vulnerability (no active exploit, no data exposure)
          required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the security concern or improvement
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What type of security concern is this?
      options:
        - Authentication/Authorization
        - Cryptography
        - Input Validation
        - Rate Limiting
        - Session Management
        - Dependencies/Supply Chain
        - Configuration/Hardening
        - Information Disclosure (minor)
        - Other
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Potential Impact
      description: What could happen if this isn't addressed?
    validations:
      required: true

  - type: textarea
    id: recommendation
    attributes:
      label: Recommended Fix
      description: How would you suggest fixing this?

  - type: textarea
    id: references
    attributes:
      label: References
      description: Links to related CVEs, OWASP guidelines, or security best practices
      placeholder: |
        - OWASP Top 10: ...
        - CWE: ...
        - Related issues: ...
