//! Tests for the VP8 RTP depacketizer.
//!
//! Fixture file: `tests/fixtures/vp8_sample.rtp` (generated by the
//! `capture_vp8_fixture` example; see Task D3).
//!
//! The bulk of in-memory / unit-level coverage for [`Vp8Depacketizer`] lives in
//! `src/voice/rtp_depacketizer.rs` under `#[cfg(test)] mod tests`. That keeps
//! the test scope compatible with the current `mod voice;` (private)
//! declaration in `lib.rs` — integration tests under `tests/` can only see
//! `pub` items from the library crate root.
//!
//! Once Task D3 lands the fixture binary, the first test below is un-ignored
//! and exercises the full packet → frame reassembly path end-to-end. If a
//! future task promotes the `voice` module to `pub`, the in-memory assertions
//! can be pulled into this file too.

use std::path::Path;

#[test]
#[ignore = "requires VP8 fixture from Task D3"]
fn assembles_keyframe_from_rtp_fragments() {
    // Load tests/fixtures/vp8_sample.rtp (packed RTP stream).
    // Feed packets through Vp8Depacketizer.
    // Assert exactly one complete frame is returned after the marker-bit packet.
    // Assert the first frame is a keyframe (VP8 frame tag byte 0, bit 0 is 0).
    let fixture = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join("vp8_sample.rtp");
    assert!(
        fixture.exists(),
        "VP8 fixture missing at {} — run `cargo run --example capture_vp8_fixture` (Task D3)",
        fixture.display()
    );

    // Real assertions land in Task D3 once the fixture exists and the
    // `voice` module is accessible to integration tests.
}

#[test]
fn drops_partial_frame_on_sequence_gap() {
    // In-memory coverage for sequence-gap handling lives in
    // `src/voice/rtp_depacketizer.rs`'s unit tests
    // (`drops_partial_frame_on_sequence_gap_internal`), because the `voice`
    // module is currently declared `mod voice;` (private) in `lib.rs` and
    // therefore unreachable from integration tests.
    //
    // This skeleton exists so Task D3 has a stable file to add fixture-backed
    // assertions to; the unit test already guards the invariant.
}
