//! `OpenAPI` Documentation
//!
//! Central `OpenAPI` definition using utoipa. Serves Swagger UI at `/api/docs`.

#![expect(
    clippy::needless_for_each,
    reason = "triggered by utoipa OpenApi derive macro"
)]

use utoipa::openapi::security::{HttpAuthScheme, HttpBuilder, SecurityScheme};
use utoipa::{Modify, OpenApi};

/// `OpenAPI` documentation for the `Kaiku` API.
#[derive(OpenApi)]
#[openapi(
    info(
        title = "Kaiku API",
        description = "Self-hosted voice and text chat platform API",
        version = "0.1.0",
        license(name = "MIT OR Apache-2.0"),
    ),
    tags(
        (name = "health", description = "Health check endpoints"),
        (name = "auth", description = "Authentication and user management"),
        (name = "channels", description = "Channel management"),
        (name = "messages", description = "Message operations"),
        (name = "dm", description = "Direct message conversations"),
        (name = "guilds", description = "Guild (server) management"),
        (name = "roles", description = "Role management"),
        (name = "invites", description = "Guild invite management"),
        (name = "categories", description = "Channel category management"),
        (name = "emojis", description = "Custom emoji management"),
        (name = "search", description = "Search endpoints"),
        (name = "admin", description = "System administration"),
        (name = "moderation", description = "Content moderation and reports"),
        (name = "social", description = "Friends and block list"),
        (name = "voice", description = "Voice channel and WebRTC"),
        (name = "crypto", description = "E2EE key management"),
        (name = "bots", description = "Bot and application management"),
        (name = "commands", description = "Slash command management"),
        (name = "webhooks", description = "Webhook management"),
        (name = "pins", description = "User pin management"),
        (name = "favorites", description = "Channel favorites"),
        (name = "reactions", description = "Message reactions"),
        (name = "unread", description = "Unread message tracking"),
        (name = "preferences", description = "User preferences"),
        (name = "pages", description = "Platform and guild pages"),
        (name = "connectivity", description = "Connection and session info"),
        (name = "discovery", description = "Public guild discovery and browsing"),
        (name = "governance", description = "Data export and account deletion"),
        (name = "workspaces", description = "Personal workspace management"),
        (name = "settings", description = "Server settings and configuration"),
        (name = "setup", description = "Initial server setup"),
        (name = "uploads", description = "File upload operations"),
        (name = "overrides", description = "Channel permission overrides"),
        (name = "screenshare", description = "Screen sharing"),
    ),
    modifiers(&SecurityAddon),
    paths(
        // Health
        crate::api::health_check,
        // Auth - public
        crate::auth::register::register,
        crate::auth::login::login,
        crate::auth::login::refresh_token,
        crate::auth::login::forgot_password,
        crate::auth::login::reset_password,
        crate::auth::login::oidc_providers,
        crate::auth::login::oidc_authorize,
        crate::auth::login::oidc_callback,
        // Auth - protected
        crate::auth::login::logout,
        crate::auth::profile::get_profile,
        crate::auth::profile::update_profile,
        crate::auth::profile::upload_avatar,
        crate::auth::mfa::mfa_setup,
        crate::auth::mfa::mfa_verify,
        crate::auth::mfa::mfa_disable,
        crate::auth::mfa::mfa_generate_backup_codes,
        crate::auth::mfa::mfa_backup_code_count,
        crate::auth::sessions::list_sessions,
        crate::auth::sessions::revoke_session,
        crate::auth::sessions::revoke_all_other_sessions,
        // Channels
        crate::chat::channels::create,
        crate::chat::channels::get,
        crate::chat::channels::update,
        crate::chat::channels::delete,
        crate::chat::channels::list_members,
        crate::chat::channels::add_member,
        crate::chat::channels::remove_member,
        crate::chat::channels::mark_as_read,
        // Messages
        crate::chat::messages::list,
        crate::chat::messages::create,
        crate::chat::messages::update,
        crate::chat::messages::delete,
        crate::chat::messages::list_thread_replies,
        crate::chat::messages::mark_thread_read,
        // Uploads
        crate::chat::uploads::upload_message_with_file,
        crate::chat::uploads::upload_file,
        crate::chat::uploads::get_attachment,
        crate::chat::uploads::get_signed_url,
        crate::chat::uploads::download,
        // DM
        crate::chat::dm::list_dms,
        crate::chat::dm::create_dm,
        crate::chat::dm::get_dm,
        crate::chat::dm::leave_dm,
        crate::chat::dm::update_dm_name,
        crate::chat::dm::mark_as_read,
        crate::chat::dm::mark_all_dms_read,
        crate::chat::dm::upload_dm_icon,
        crate::chat::dm::get_dm_icon,
        // DM Search
        crate::chat::dm_search::search_dm_messages,
        // Overrides
        crate::chat::overrides::list_overrides,
        crate::chat::overrides::set_override,
        crate::chat::overrides::delete_override,
        // Guilds
        crate::guild::core::list_guilds,
        crate::guild::core::create_guild,
        crate::guild::core::get_guild,
        crate::guild::core::update_guild,
        crate::guild::core::delete_guild,
        crate::guild::members::leave_guild,
        crate::guild::members::list_members,
        crate::guild::members::kick_member,
        crate::guild::settings::list_channels,
        crate::guild::settings::reorder_channels,
        crate::guild::settings::mark_all_channels_read,
        crate::guild::bots::list_guild_bots,
        crate::guild::bots::add_bot_to_guild,
        crate::guild::bots::remove_bot_from_guild,
        crate::guild::bots::list_guild_commands,
        crate::guild::settings::get_guild_settings,
        crate::guild::settings::update_guild_settings,
        crate::guild::settings::get_guild_usage,
        // Roles
        crate::guild::roles::list_roles,
        crate::guild::roles::create_role,
        crate::guild::roles::update_role,
        crate::guild::roles::delete_role,
        crate::guild::roles::assign_role,
        crate::guild::roles::remove_role,
        // Invites
        crate::guild::invites::list_invites,
        crate::guild::invites::create_invite,
        crate::guild::invites::delete_invite,
        crate::guild::invites::join_via_invite,
        // Categories
        crate::guild::categories::list_categories,
        crate::guild::categories::create_category,
        crate::guild::categories::update_category,
        crate::guild::categories::delete_category,
        crate::guild::categories::reorder_categories,
        // Emojis
        crate::guild::emojis::list_emojis,
        crate::guild::emojis::get_emoji,
        crate::guild::emojis::create_emoji,
        crate::guild::emojis::update_emoji,
        crate::guild::emojis::delete_emoji,
        // Guild Search
        crate::guild::search::search_messages,
        // Discovery
        crate::discovery::handlers::browse_guilds,
        crate::discovery::handlers::join_discoverable,
        // Guild Pages
        crate::pages::guild_pages::list_guild_pages,
        crate::pages::guild_pages::create_guild_page,
        crate::pages::guild_pages::update_guild_page,
        crate::pages::guild_pages::delete_guild_page,
        crate::pages::guild_pages::reorder_guild_pages,
        crate::pages::guild_pages::get_guild_page,
        crate::pages::guild_pages::accept_guild_page,
        // Admin
        crate::admin::system::get_admin_status,
        crate::admin::system::get_admin_stats,
        crate::admin::system::elevate_session,
        crate::admin::system::de_elevate_session,
        crate::admin::users::list_users,
        crate::admin::users::export_users_csv,
        crate::admin::users::get_user_details,
        crate::admin::guilds::list_guilds,
        crate::admin::guilds::export_guilds_csv,
        crate::admin::guilds::get_guild_details,
        crate::admin::audit::get_audit_log,
        crate::moderation::admin_handlers::list_reports,
        crate::moderation::admin_handlers::report_stats,
        crate::moderation::admin_handlers::get_report,
        crate::moderation::admin_handlers::claim_report,
        crate::moderation::admin_handlers::resolve_report,
        crate::admin::users::ban_user,
        crate::admin::users::unban_user,
        crate::admin::users::bulk_ban_users,
        crate::admin::users::delete_user,
        crate::admin::guilds::suspend_guild,
        crate::admin::guilds::unsuspend_guild,
        crate::admin::guilds::bulk_suspend_guilds,
        crate::admin::guilds::delete_guild,
        crate::admin::system::create_announcement,
        crate::admin::system::get_auth_settings,
        crate::admin::system::update_auth_settings,
        crate::admin::system::list_oidc_providers,
        crate::admin::system::create_oidc_provider,
        crate::admin::system::update_oidc_provider,
        crate::admin::system::delete_oidc_provider,
        // Moderation
        crate::moderation::handlers::create_report,
        crate::moderation::filter_handlers::list_filter_configs,
        crate::moderation::filter_handlers::update_filter_configs,
        crate::moderation::filter_handlers::list_custom_patterns,
        crate::moderation::filter_handlers::create_custom_pattern,
        crate::moderation::filter_handlers::update_custom_pattern,
        crate::moderation::filter_handlers::delete_custom_pattern,
        crate::moderation::filter_handlers::list_moderation_log,
        crate::moderation::filter_handlers::test_filter,
        // Social
        crate::social::friends::send_friend_request,
        crate::social::friends::list_friends,
        crate::social::friends::list_pending_requests,
        crate::social::friends::list_blocked,
        crate::social::friends::accept_friend_request,
        crate::social::friends::reject_friend_request,
        crate::social::friends::block_user,
        crate::social::friends::unblock_user,
        crate::social::friends::remove_friend,
        // Voice
        crate::voice::handlers::get_ice_servers,
        crate::voice::call_handlers::get_call,
        crate::voice::call_handlers::start_call,
        crate::voice::call_handlers::join_call,
        crate::voice::call_handlers::decline_call,
        crate::voice::call_handlers::leave_call,
        // Screen share
        crate::chat::screenshare::check,
        crate::chat::screenshare::start,
        crate::chat::screenshare::stop,
        // Crypto
        crate::crypto::upload_keys,
        crate::crypto::get_backup,
        crate::crypto::upload_backup,
        crate::crypto::get_backup_status,
        crate::crypto::get_own_devices,
        crate::crypto::get_user_keys,
        crate::crypto::claim_prekey,
        // Bots
        crate::bots::list_applications,
        crate::bots::create_application,
        crate::bots::get_application,
        crate::bots::delete_application,
        crate::bots::create_bot,
        crate::bots::reset_bot_token,
        crate::bots::update_gateway_intents,
        // Commands
        crate::bots::commands::list_commands,
        crate::bots::commands::register_commands,
        crate::bots::commands::delete_all_commands,
        crate::bots::commands::delete_command,
        // Webhooks
        crate::webhooks::handlers::list_webhooks,
        crate::webhooks::handlers::create_webhook,
        crate::webhooks::handlers::get_webhook,
        crate::webhooks::handlers::update_webhook,
        crate::webhooks::handlers::delete_webhook,
        crate::webhooks::handlers::test_webhook,
        crate::webhooks::handlers::list_deliveries,
        // Reactions
        crate::chat::reactions::get_reactions,
        crate::chat::reactions::add_reaction,
        crate::chat::reactions::remove_reaction,
        // Pins
        crate::chat::pins::list_pins,
        crate::chat::pins::create_pin,
        crate::chat::pins::reorder_pins,
        crate::chat::pins::update_pin,
        crate::chat::pins::delete_pin,
        // Favorites
        crate::favorites::list_favorites,
        crate::favorites::reorder_channels,
        crate::favorites::reorder_guilds,
        crate::favorites::add_favorite,
        crate::favorites::remove_favorite,
        // Workspaces
        crate::workspaces::handlers::create_workspace,
        crate::workspaces::handlers::list_workspaces,
        crate::workspaces::handlers::get_workspace,
        crate::workspaces::handlers::update_workspace,
        crate::workspaces::handlers::delete_workspace,
        crate::workspaces::handlers::add_entry,
        crate::workspaces::handlers::remove_entry,
        crate::workspaces::handlers::reorder_entries,
        crate::workspaces::handlers::reorder_workspaces,
        // Unread
        crate::chat::unread::get_unread_aggregate,
        crate::chat::unread::mark_all_read,
        // Preferences
        crate::preferences::get_preferences,
        crate::preferences::update_preferences,
        // Connectivity
        crate::connectivity::get_summary,
        crate::connectivity::get_sessions,
        crate::connectivity::get_session_detail,
        // Pages
        crate::pages::platform::list_platform_pages,
        crate::pages::platform::get_platform_page,
        crate::pages::platform::create_platform_page,
        crate::pages::platform::get_pending_acceptance,
        crate::pages::platform::reorder_platform_pages,
        crate::pages::platform::update_platform_page,
        crate::pages::platform::delete_platform_page,
        crate::pages::platform::accept_page,
        // Settings
        crate::settings::get_server_settings,
        crate::settings::get_upload_limits,
        crate::settings::get_instance_limits,
        // Setup
        crate::setup::status,
        crate::setup::get_config,
        crate::setup::complete,
        // Global Search
        crate::search::search_all,
        // Data Governance
        crate::governance::handlers::request_export,
        crate::governance::handlers::get_export_status,
        crate::governance::handlers::download_export,
        crate::governance::handlers::request_deletion,
        crate::governance::handlers::cancel_deletion,
    ),
    components(schemas(
        // Health
        crate::api::HealthResponse,
        // Auth
        crate::auth::types::RegisterRequest,
        crate::auth::types::LoginRequest,
        crate::auth::types::RefreshRequest,
        crate::auth::types::LogoutRequest,
        crate::auth::types::AuthResponse,
        crate::auth::types::UserProfile,
        crate::auth::types::MfaSetupResponse,
        crate::auth::types::MfaBackupCodesResponse,
        crate::auth::types::MfaBackupCodeCountResponse,
        crate::auth::types::MfaVerifyRequest,
        crate::auth::types::UpdateProfileRequest,
        crate::auth::types::UpdateProfileResponse,
        crate::auth::types::ForgotPasswordRequest,
        crate::auth::types::ResetPasswordRequest,
        crate::auth::types::SessionInfo,
        crate::auth::types::SessionListResponse,
        crate::auth::types::RevokeAllResponse,
        crate::auth::error::ErrorResponse,
        // DB Models
        crate::db::AuthMethod,
        crate::db::UserStatus,
        crate::db::ChannelType,
        crate::db::Channel,
        // Note: db::User intentionally excluded — contains password_hash, mfa_secret
        crate::db::Message,
        crate::db::Role,
        crate::db::FileAttachment,
        crate::db::PublicOidcProvider,
        crate::db::AuthMethodsConfig,
        crate::db::ChannelUnread,
        crate::db::GuildUnreadSummary,
        crate::db::UnreadAggregate,
        crate::db::BotApplication,
        crate::db::SlashCommand,
        crate::db::GuildBotInstallation,
        // Chat - Channels
        crate::chat::types::ChannelResponse,
        crate::chat::types::CreateChannelRequest,
        crate::chat::types::UpdateChannelRequest,
        crate::chat::types::AddMemberRequest,
        crate::chat::types::MemberResponse,
        crate::chat::types::MarkChannelAsReadRequest,
        // Chat - Messages
        crate::chat::types::AuthorProfile,
        crate::chat::types::AttachmentInfo,
        crate::chat::types::MentionType,
        crate::chat::types::ThreadInfoResponse,
        crate::chat::types::MessageResponse,
        crate::chat::types::ReactionInfo,
        crate::chat::types::ListMessagesQuery,
        crate::chat::types::CreateMessageRequest,
        crate::chat::types::ListThreadRepliesQuery,
        crate::chat::types::UpdateMessageRequest,
        crate::chat::types::CursorPaginatedResponse<crate::chat::types::MessageResponse>,
        // Chat - DM
        crate::chat::types::CreateDMRequest,
        crate::chat::types::DMResponse,
        crate::chat::types::LastMessagePreview,
        crate::chat::types::DMListResponse,
        crate::chat::types::DMParticipant,
        crate::chat::types::UpdateDMNameRequest,
        crate::chat::types::DMIconResponse,
        crate::chat::types::MarkAsReadRequest,
        crate::chat::types::MarkAsReadResponse,
        // Chat - DM Search
        crate::chat::types::DmSearchQuery,
        crate::chat::types::DmSearchAuthor,
        crate::chat::types::DmSearchResult,
        crate::chat::types::DmSearchResponse,
        // Chat - Overrides
        crate::chat::types::OverrideResponse,
        crate::chat::types::SetOverrideRequest,
        // Guild
        crate::guild::types::Guild,
        crate::guild::types::GuildWithMemberCount,
        crate::guild::types::CreateGuildRequest,
        crate::guild::types::UpdateGuildRequest,
        crate::guild::types::JoinGuildRequest,
        crate::guild::types::GuildMember,
        crate::guild::types::GuildInvite,
        crate::guild::types::CreateInviteRequest,
        crate::guild::types::InviteResponse,
        crate::guild::types::CreateRoleRequest,
        crate::guild::types::UpdateRoleRequest,
        crate::guild::types::RoleResponse,
        crate::guild::types::GuildEmoji,
        crate::guild::types::CreateEmojiRequest,
        crate::guild::types::UpdateEmojiRequest,
        crate::guild::types::GuildSettings,
        crate::guild::types::UpdateGuildSettingsRequest,
        crate::guild::types::GuildCommandInfo,
        crate::guild::settings::UsageStat,
        crate::guild::settings::GuildUsageStats,
        crate::guild::settings::ChannelWithUnread,
        crate::guild::bots::InstalledBot,
        crate::guild::settings::ChannelPosition,
        crate::guild::settings::ReorderChannelsRequest,
        // Guild - Categories
        crate::guild::categories::Category,
        crate::guild::categories::CreateCategoryRequest,
        crate::guild::categories::UpdateCategoryRequest,
        crate::guild::categories::ReorderRequest,
        crate::guild::categories::CategoryPosition,
        // Discovery
        crate::discovery::types::DiscoverSort,
        crate::discovery::types::DiscoverableGuild,
        crate::discovery::types::DiscoverResponse,
        crate::discovery::types::JoinDiscoverableResponse,
        // Guild - Search
        crate::guild::search::SearchQuery,
        crate::guild::search::SearchAuthor,
        crate::guild::search::SearchResult,
        crate::guild::search::SearchResponse,
        // Admin
        crate::admin::types::ElevateRequest,
        crate::admin::types::ElevateResponse,
        crate::admin::types::GlobalBanRequest,
        crate::admin::types::SuspendGuildRequest,
        crate::admin::types::CreateAnnouncementRequest,
        crate::admin::types::AdminStatusResponse,
        crate::admin::types::AdminStatsResponse,
        crate::admin::types::BulkBanRequest,
        crate::admin::types::BulkBanResponse,
        crate::admin::types::BulkSuspendRequest,
        crate::admin::types::BulkSuspendResponse,
        crate::admin::types::BulkActionFailure,
        crate::admin::shared::PaginationParams,
        crate::admin::audit::AuditLogParams,
        crate::admin::users::UserSummary,
        crate::admin::guilds::GuildSummary,
        crate::admin::audit::AuditLogEntryResponse,
        crate::admin::system::DeElevateResponse,
        crate::admin::users::UserGuildMembership,
        crate::admin::users::UserDetailsResponse,
        crate::admin::guilds::GuildMemberInfo,
        crate::admin::guilds::GuildOwnerInfo,
        crate::admin::guilds::GuildDetailsResponse,
        crate::admin::shared::PaginatedResponse<crate::admin::users::UserSummary>,
        crate::admin::shared::PaginatedResponse<crate::admin::guilds::GuildSummary>,
        crate::admin::shared::PaginatedResponse<crate::admin::audit::AuditLogEntryResponse>,
        crate::admin::shared::DeleteResponse,
        crate::admin::system::AnnouncementResponse,
        crate::admin::system::AuthSettingsResponse,
        crate::admin::system::OidcProviderResponse,
        // Social
        crate::social::types::FriendshipStatus,
        crate::social::types::Friendship,
        crate::social::types::Friend,
        crate::social::types::SendFriendRequestBody,
        // Moderation
        crate::moderation::types::ReportCategory,
        crate::moderation::types::ReportStatus,
        crate::moderation::types::ReportTargetType,
        crate::moderation::types::CreateReportRequest,
        crate::moderation::types::ResolveReportRequest,
        crate::moderation::types::ListReportsQuery,
        crate::moderation::types::Report,
        crate::moderation::types::ReportResponse,
        crate::moderation::types::ReportStatsResponse,
        crate::moderation::types::PaginatedReports,
        // Moderation - Filters
        crate::moderation::filter_types::FilterCategory,
        crate::moderation::filter_types::FilterAction,
        crate::moderation::filter_types::GuildFilterConfig,
        crate::moderation::filter_types::GuildFilterPattern,
        crate::moderation::filter_types::CreatePatternRequest,
        crate::moderation::filter_types::UpdatePatternRequest,
        crate::moderation::filter_types::UpdateFilterConfigsRequest,
        crate::moderation::filter_types::TestFilterRequest,
        crate::moderation::filter_types::TestFilterResponse,
        crate::moderation::filter_types::FilterMatchResponse,
        crate::moderation::filter_types::PaginatedModerationLog,
        // Voice - Calls
        crate::voice::call_handlers::CallStateResponse,
        crate::voice::call_handlers::CallApiError,
        crate::voice::call::CallState,
        // Bots
        crate::bots::CreateApplicationRequest,
        crate::bots::ApplicationResponse,
        crate::bots::BotTokenResponse,
        // Workspaces
        crate::workspaces::types::WorkspaceResponse,
        crate::workspaces::types::WorkspaceListItem,
        crate::workspaces::types::WorkspaceEntryResponse,
        crate::workspaces::types::WorkspaceDetailResponse,
        crate::workspaces::types::CreateWorkspaceRequest,
        crate::workspaces::types::UpdateWorkspaceRequest,
        crate::workspaces::types::AddEntryRequest,
        crate::workspaces::types::ReorderEntriesRequest,
        crate::workspaces::types::ReorderWorkspacesRequest,
        // Settings
        crate::settings::InstanceLimitsResponse,
        // Data Governance
        crate::governance::types::ExportJobResponse,
        crate::governance::types::DeleteAccountRequest,
        crate::governance::types::DeleteAccountResponse,
        crate::governance::types::CancelDeletionResponse,
    ))
)]
pub struct ApiDoc;

struct SecurityAddon;

impl Modify for SecurityAddon {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        let components = openapi.components.get_or_insert_with(Default::default);
        components.add_security_scheme(
            "bearer_auth",
            SecurityScheme::Http(
                HttpBuilder::new()
                    .scheme(HttpAuthScheme::Bearer)
                    .bearer_format("JWT")
                    .build(),
            ),
        );
    }
}
